version: "3.8"

services:
  webservice:
   # hostname: fom-webservice
    image: deluckii/fom:latest
    ports:
      - "8080:8080"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

# docker stack deploy -c webservice-docker.yaml webservice-fom
# docker service ls
# docker stack rm webservice-fom